### ISSUE TITLE
Add option to ignore or respect trailing slashes

### ISSUE THREAD

**Issue by gearsdigital** [bnomei/kirby3-redirects#10]
I wonder if it would make sense to have an option to define wether a trailing slash is respected or  not. Right now I need to add two redirects for the same resource.

1.`/test -> /test-new`
2. `/test/ -> /test-new`

We could surly add a rule to the `.htaccess` and remove all trailing slashes intially but that would result in two redirects (one by the webserver and one by your plugin) which is a bit messy and totally unnecessary.

What do you think about that idea?

**Comment by bnomei** [comment]
supported in 1.5.3

**Comment by gearsdigital** [comment]
Awesome! Thank you for fixing this 👍
