### ISSUE TITLE
Error on plugin installation

### ISSUE THREAD

**Issue by DominiqueVial** [bnomei/kirby3-redirects#14]
After I installed the plugin, an error occured.
`Class "Bnomei\Redirects" not found` on `/site/plugins/kirby3-redirects/index.php29` 

No  data have been added to `site.txt`.
Removing plugin make the website work again.

Any idea?

### Notes

- installation was made using Composer
- Current PHP version is 8.0.12
- Kirby is up to date: 3.6.0
- behavior is weird as sometimes the error only came after accessing 2 or 3 URL on the website...

![Capture d’écran 2021-11-30 à 06 44 07](https://user-images.githubusercontent.com/43033637/143992590-ea776090-e463-4fad-99e4-ae82c7d56796.jpg)

**Comment by bnomei** [comment]
i double checked how the classes are loaded. think its done properly. what is you local devenviroment (osx valet, MAMP, ...)? or does it happen on a production LAMP stack as well?

**Comment by bnomei** [comment]
the route:before should always be triggered after all plugins are loaded.
