### ISSUE TITLE
Order fails by hits / path etc.

### ISSUE THREAD

**Issue by lexislav** [bnomei/kirby3-redirects#21]
Is there any plan to add possibility to order failure's list by other columns then ID?

It might be useful to solve issues with most hits first.

**Comment by bnomei** [comment]
sorry i dont understand your question. my redirects plugin just resolves the redirect but not track any hits (like the retour plugin does).
where exactly do you have that ID column? in the panel section of this plugin? in the resolving code?

**Comment by lexislav** [comment]
sorry, I have commited this to wrong repository :-( You are right, it is about retour plugin. My apologies.
