### ISSUE TITLE
Redirects not working in Kirby 4?

### ISSUE THREAD

**Issue by trey** [bnomei/kirby3-redirects#25]
After upgrading to Kirby 4, any URL I have saved as a redirect is returning a 404.

Any advice on what I might be doing wrong?

- Kirby 4.0.1
- Redirects 1.12.0

**Comment by bnomei** [comment]
sorry for the late reply. i will investigate and report back. did you use placeholders in your FROM parameters?

**Comment by bnomei** [comment]
will be fixed with upcoming major version. please remove and require again via composer to upgrade

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-redirects/releases/tag/v4.0.0

**Comment by trey** [comment]
Thank you! I don't think I was using any placeholders, but I can't fully remember now! 😄
