### ISSUE TITLE
Current Kirby version requirements?

### ISSUE THREAD

**Issue by splorp** [bnomei/kirby3-redirects#26]
Hi Bruno.

I have yet to install the 4.2.0 version of the plugin on my K3 site, mainly because the Kirby version requirements are not mentioned anywhere.

I did notice that `composer.json` does not list `getkirby/cms` in the `require` element, but it does list it for `require-dev`.

```
"require": {
    "php": ">=8.1",
    "getkirby/composer-installer": "^1.2"
},
"require-dev": {
    "getkirby/cms": "^4.1.0",
    "php-coveralls/php-coveralls": "^2.4",
    "phpunit/phpunit": "^9.5",
    "spatie/ray": "^1.41"
},
```

Can I assume that 4.2.0 still works with K3?

**Comment by bnomei** [comment]
plugin v3 for kirby 3
plugin v4 for kirby 4

i will add the required version in composer asap

**Comment by splorp** [comment]
Thanks!
