### ISSUE TITLE
Default error page does not display when cache disabled

### ISSUE THREAD

**Issue by splorp** [bnomei/kirby3-redirects#27]
I have disabled the cache for the redirects plugin in my local development environment using the following config setting [suggested by you](https://forum.getkirby.com/t/disabling-cache-for-plugins-updates-et-al/31176/6) in the Kirby Forum:

```PHP
return [
   'bnomei.redirects.cache' => false,
];
```

However, when requesting a nonexistant page, rather than the default [error page]() being displayed, Kirby throws an error.

`Call to undefined method Kirby\Cache\NullCache::root()`

This is happening in the `validRoutesDir()` function located in `Redirects.php`.

```PHP
public function validRoutesDir(): string
    {
        $dir = kirby()->cache('bnomei.redirects')->root() . '/validroutes';
        if (!Dir::exists($dir)) {
            Dir::make($dir);
        }
        return $dir;
    }
```

**Comment by bnomei** [comment]
solved in v5 as released today
