### ISSUE TITLE
Control through 'Settings' page?

### ISSUE THREAD

**Issue by louiswalch** [bnomei/kirby3-redirects#8]
Is it possible to have this added to the 'Settings' page rather then the Panel dashboard?

**Comment by bnomei** [comment]
as far as i know it is currently not possible to extend the core settings.
but alternative @distantnative retour plugin is using panel-views and that might be a step into the direction you are looking for.

**Comment by bnomei** [comment]
https://forum.getkirby.com/t/how-to-populate-settings-page/12248/4?u=bnomei
